
import React from 'react';

const Disclaimer: React.FC = () => {
  return (
    <section id="disclaimer" className="py-24">
      <div className="container mx-auto px-4">
        <div className="max-w-4xl mx-auto">
          <div className="text-center mb-12">
            <h2 className="text-3xl md:text-4xl font-bold mb-4 text-white">Legal Disclaimer</h2>
            <p className="text-gray-300">Please read this disclaimer carefully before using our AI tools</p>
          </div>
          
          <div className="glass-morphism rounded-2xl p-8">
            <div className="space-y-6 text-gray-300">
              <p>
                <span className="text-neon-cyan font-bold">Educational & Entertainment Purposes Only:</span> The Phenomenon Explorer AI Suite, including all its associated tools (UFO Investigation GPT, Supernatural Myths GPT, Cryptozoology Report GPT, and Ghost Hunting GPT), is provided strictly for educational, entertainment, and research purposes only.
              </p>
              
              <p>
                <span className="text-neon-cyan font-bold">No Professional Advice:</span> The content, outputs, analyses, and reports generated by our AI tools do not constitute professional, legal, scientific, or investigative advice. Users should not rely on our tools for making legal decisions, scientific conclusions, or as a substitute for professional consultation.
              </p>
              
              <p>
                <span className="text-neon-cyan font-bold">No Endorsement of Claims:</span> AI Web Tools LLC does not endorse, validate, or confirm the existence of paranormal phenomena, UFOs, cryptids, ghosts, or any supernatural entities or events. Our tools analyze information based on user inputs and available data without making claims about the reality of such phenomena.
              </p>
              
              <p>
                <span className="text-neon-cyan font-bold">User Responsibility:</span> Users are solely responsible for how they utilize the information, reports, and analyses generated by our tools. Users must exercise their own judgment when interpreting results and should verify any critical information independently.
              </p>
              
              <p>
                <span className="text-neon-cyan font-bold">No Warranty:</span> The Phenomenon Explorer AI Suite is provided "as is" without any warranties, expressed or implied. We do not guarantee the accuracy, completeness, or reliability of any outputs, nor the suitability of our tools for any particular purpose.
              </p>
              
              <p>
                <span className="text-neon-cyan font-bold">Hypothetical Scenarios:</span> Any analyses of paranormal scenarios, legal defenses, investigative recommendations, or scientific explanations provided by our tools are purely hypothetical and should be treated as speculative explorations rather than definitive conclusions.
              </p>
              
              <p>
                <span className="text-neon-cyan font-bold">Privacy & Data:</span> While our tools may request information to provide more accurate analyses, users should exercise caution when sharing sensitive personal data. Review our Privacy Policy for details on how we handle user information.
              </p>
              
              <p>
                <span className="text-neon-cyan font-bold">Ethical Use:</span> Users agree to use our tools ethically and responsibly. Our tools should not be used to spread misinformation, harass individuals, make false claims, or engage in any illegal activities.
              </p>
              
              <p>
                <span className="text-neon-cyan font-bold">Limitation of Liability:</span> AI Web Tools LLC, its owners, affiliates, employees, and partners are not liable for any damages, losses, or consequences arising from the use of the Phenomenon Explorer AI Suite or reliance on information generated by our tools.
              </p>
              
              <p>
                By using the Phenomenon Explorer AI Suite, you acknowledge that you have read, understood, and agree to this disclaimer. If you do not agree with any part of this disclaimer, please refrain from using our tools.
              </p>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default Disclaimer;
